### ISSUE TITLE
Feature request - consistent units in latency output

### ISSUE THREAD

**Issue by GreyArea765** [caius/fio#1]
I like to echo the fio output to a file so that I can run it through some tools to visualize latency figures with various types of graph etc.

fio does not use or have the option for a common unit in the text output, it would be ace if there was an option to fix the output to a single unit (say ms).

# Standard output using three different units for time.
4 KiB <<< /tmp (xfs /dev/dm-0): request=194 time=1.73 ms (fast)
4 KiB <<< /tmp (xfs /dev/dm-0): request=64 time=1.05 s (slow)
4 KiB <<< /tmp (xfs /dev/dm-0): request=132 time=985.0 us (fast)

Thanks.

**Comment by caius** [comment]
@GreyArea765 this is just a (woefully outdated) mirror of the upstream repository sorry. You'll want to submit your feature request there so the right people see it.
